name: my_portfolio
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  #*Icons
  cupertino_icons: ^1.0.5

  font_awesome_flutter: ^10.5.0

  #*Architecture
  stacked: ^3.4.1
  stacked_services: ^1.3.0
  responsive_builder: ^0.7.0
  get_it: ^7.2.0
  injectable: ^2.3.0
  flutter_hooks: ^0.20.0
  url_strategy: ^0.2.0

  #*Services
  url_launcher: ^6.0.12
  http: ^1.1.0

  #*Utilities
  collapsible_sidebar: ^2.0.1+2
  animated_text_kit: ^4.2.1
  simple_animations: ^4.2.0
  oktoast: ^3.1.3+1

  eva_icons_flutter: ^3.1.0
  animations: ^2.0.1
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  injectable_generator: ^2.4.0
  auto_route_generator: ^7.3.1
  build_runner: ^2.1.4
  change_app_package_name: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
